---
# file: roles/workflow_Sanger/tasks/main.yml

- name: Install Sanger workflow dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - g++
    - pkg-config
    - dh-autoreconf
    - libncurses5-dev
    - libgd2-xpm-dev
    - libboost-all-dev
    - libpstreams-dev
    - libglib2.0-dev
    - r-base
    - r-base-core
    - r-cran-rcolorbrewer
    - libxml-dom-perl
    - libxml-xpath-perl
    - libjson-perl
    - libxml-libxml-perl
  tags: libs

- name: Download CGP codebase
  get_url: url={{ item }} dest=/tmp
  with_items:
    - https://github.com/ICGC-TCGA-PanCancer/PCAP-core/archive/v1.2.2.tar.gz
    - https://github.com/cancerit/cgpVcf/archive/v1.2.2.tar.gz
    - https://github.com/cancerit/alleleCount/archive/v1.2.1.tar.gz
    - https://github.com/cancerit/ascatNgs/archive/v1.4.1.tar.gz
    - https://github.com/cancerit/cgpPindel/archive/v1.1.1.tar.gz
    - https://github.com/cancerit/cgpCaVEManWrapper/archive/v1.2.0.tar.gz
    - https://github.com/cancerit/cgpCaVEManPostProcessing/archive/v1.0.2.tar.gz
    - https://github.com/cancerit/BRASS/archive/v2.0.0.tar.gz
    - https://github.com/cancerit/VAGrENT/archive/v2.0.0.tar.gz
    - https://github.com/cancerit/grass/archive/v1.0.1.tar.gz
  tags: Sanger_codebase_download

- name: Install Sanger codebase
  command: 
  args:
     chdir: /tmp






