---
# Install Dependencies for DEWrapper Workflow, and perform setup.
- name: Install DEWrapper workflow dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python
    - openjdk-7-jdk

- name: Download get-pip
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/get-pip.py

- name: Install pip
  sudo: True
  shell: python /tmp/get-pip.py

- name: Install docker-py
  sudo: True
  pip: name=docker-py

- name: Install AWS CLI
  sudo: True
  pip: name=awscli

- name: Setup aws config directory
  sudo: true
  file: state=directory path=/home/ubuntu/.aws owner=ubuntu

- name: Copy over aws config
  sudo_user: 'ubuntu'
  template: src=config.j2 dest=/home/ubuntu/.aws/config 

- name: Copy over DKFZ image 
  sudo_user: 'ubuntu'
  shell: creates=/home/ubuntu/dkfz_dockered_workflows_1.0.132-2.tar aws s3 cp s3://oicr.docker.private.images/dkfz_dockered_workflows_1.0.132-2.tar /home/ubuntu/dkfz_dockered_workflows_1.0.132-2.tar 

  #NOTE: Not sure, but it seems to me that Ansible unarchive module prefers .tgz to .tar.gz
- name: Copy over bundledFiles supporting DKFZ container
  sudo_user: 'ubuntu'
  shell: creates=/home/ubuntu/dkfz-workflow-dependencies_150218_0931.tgz aws s3 cp s3://oicr.docker.private.images/dkfz-workflow-dependencies_150218_0931.tar.gz /home/ubuntu/dkfz-workflow-dependencies_150218_0931.tgz

- name: Get docker container seqware_whitestar
  docker:
    image: seqware/seqware_whitestar:1.1.1

- name: Get docker container pcawg-delly-workflow
  docker:
    image: pancancer/pcawg-delly-workflow:1.0

- name: Get docker container pancancer_upload_download
  docker:
    image: pancancer/pancancer_upload_download:1.1

- name: Load DKFZ image
  shell: docker load -i /home/ubuntu/dkfz_dockered_workflows_1.0.132-2.tar
  
- name: Setup bundled files
  sudo: true
  file: path=/datastore/DEWorkflowData/dkfz/32749c9f-d8aa-4ff5-b32c-296976aec706/bundledFiles state=directory owner=ubuntu

# Before running unarchive, check that a random file in thebundle  isn't already unarchived: the unarchive module will take a very long time to run,
# even if the file is already unarchived. 
- name: check if already unarchived
  stat: path=/datastore/DEWorkflowData/dkfz/32749c9f-d8aa-4ff5-b32c-296976aec706/bundledFiles/annovar/annovar_Sept2013/mousedb/mm10_seq/chrUn_GL456394.fa
  sudo_user: 'ubuntu'
  register: bundledFilesStat

- name: Create workflows directory
  sudo: yes
  file: path=/workflows state=directory owner=ubuntu group=ubuntu mode=0777

- name: check if /datastore already exists
  stat: path=/datastore
  register: datastoreStat

# This may already exists (created in another playbook), as symlink to /mnt/datastore
- name: Create datastore directory
  sudo: yes
  file: path=/datastore state=directory owner=ubuntu group=ubuntu mode=0777
  when: not datastoreStat.stat.exists
  
- name: Untar bundledFiles
  sudo_user: 'ubuntu'
  unarchive: src=/home/ubuntu/dkfz-workflow-dependencies_150218_0931.tgz dest=/datastore/DEWorkflowData/dkfz/32749c9f-d8aa-4ff5-b32c-296976aec706/bundledFiles copy=no
  when: not bundledFilesStat.stat.exists

- name: Get Seqware artifact
  sudo_user: 'ubuntu'
  get_url: dest=/home/ubuntu/seqware-distribution-{{ seqware_version }}-full.jar url=https://seqwaremaven.oicr.on.ca/artifactory/seqware-release/com/github/seqware/seqware-distribution/{{ seqware_version }}/seqware-distribution-{{ seqware_version }}-full.jar

- name: Get DEWrapperWorkflow
  get_url: url=https://s3.amazonaws.com/oicr.workflow.bundles/released-bundles/Workflow_Bundle_DEWrapperWorkflow_{{ dewrapper_workflow_version }}_SeqWare_1.1.0.zip dest=/home/ubuntu/Workflow_Bundle_DEWrapperWorkflow_{{ dewrapper_workflow_version }}_SeqWare_1.1.0.zip

- name: Unzip DEWrapperWorkflow
  sudo_user: 'ubuntu'
  shell: java -cp /home/ubuntu/seqware-distribution-{{ seqware_version }}-full.jar net.sourceforge.seqware.pipeline.tools.UnZip --input-zip /home/ubuntu/Workflow_Bundle_DEWrapperWorkflow_{{ dewrapper_workflow_version }}_SeqWare_1.1.0.zip --output-dir /workflows/Workflow_Bundle_DEWrapperWorkflow_{{ dewrapper_workflow_version }}_SeqWare_1.1.0 creates=/workflows/Workflow_Bundle_DEWrapperWorkflow_{{ dewrapper_workflow_version }}_SeqWare_1.1.0

- name: Get workflow launcher script
  sudo_user: 'ubuntu'
  get_url: dest=/home/ubuntu//launchWorkflow.sh url=https://raw.githubusercontent.com/ICGC-TCGA-PanCancer/DEWrapperWorkflow/{{ dewrapper_workflow_version }}/launchWorkflow.sh

- name: Get workflow launcher script for Whitestar
  sudo_user: 'ubuntu'
  get_url: dest=/home/ubuntu//launchWorkflowDev.sh url=https://raw.githubusercontent.com/ICGC-TCGA-PanCancer/DEWrapperWorkflow/{{ dewrapper_workflow_version }}/launchWorkflowDev.sh
