---
# file: mini-pancancer.yml
# This is a simple script run by itself to install bwa and its dependencies 
# without assuming anything about hardware

- hosts: all
  sudo: True
  roles: 
    - { role: workflow-dependencies }
    - { role: genetorrent, user_name: seqware }
    - { role: workflow-sanger-dependencies }

- hosts: master 
  sudo: True
  roles: 
    - { role: workflow , workflow_name: Sanger, workflows: Workflow_Bundle_SangerPancancerCgpCnIndelSnvStr_1.0.0_SeqWare_1.1.0-alpha.5  }
