---
# file: pancancer.yml
# A pan-cancer cluster is basically a SeqWare cluster with some additions
# to support various workflows
- include: ../seqware-bag/seqware-install.yml

- hosts: all
  sudo: True
  roles: 
    - { role: workflow-dependencies }

- hosts: master 
  sudo: True
  roles: 
    - { role: workflow-bwa }
