---
# file: pancancer.yml
# A pan-cancer cluster is basically a SeqWare cluster with some additions
# to support various workflows

# if required, here is where we would port the workaround for Bionimbus and Toyko's cloud in ubuntu_12.04_minimal script
# however, it looks like that might be redundant due to setup_volumes.pl

# do generic SeqWare setup
# this is a program for listing all ansible variables,  https://galaxy.ansible.com/list#/roles/646
#- hosts: master
#  roles:
#     - f500.dumpall


- include: ../seqware-bag/seqware-install.yml
  when: seqware_in_container is not defined or seqware_in_container = false

- include: ../seqware-bag/install-seqware-container.yml
  when: seqware_in_container is defined and seqware_in_container = true 

- hosts: master:worker
  sudo: True
  vars:
   swap_on: False
   sge_hack: False
  roles: 
    - { role: mount_device, when: device is defined }
    - { role: workflow-dependencies }
    - { role: genetorrent }
    - { role: install-docker, when: (workflow_name is defined and 'DEWrapper' in workflow_name or seqware_in_container is defined and seqware_in_container = true) } 
    - { role: workflow-bwa-dependencies, when: ( workflow_name is defined and 'BWA' in workflow_name ) }
    - { role: workflow-sanger-dependencies, when: ( workflow_name is defined and 'Sanger' in workflow_name ) }
    - { role: workflow-sanger-with-docker, when: (workflow_name is defined and 'Sanger' in workflow_name and seqware_in_container is defined and seqware_in_container = true ) }
    - { role: workflow-dewrapper-dependencies, when: (workflow_name is defined and 'DEWrapper' in workflow_name ) } 
    - { role: ebi-custom }

# 9000 equals to aproximately 10 GB of SWAP; we don't want to run the playbook if the instance already has 10 GB of SWAP because the role was most probably already applied.
    - { role: swap-enabled, when: swap_on and ansible_swaptotal_mb < 9000 }

- hosts: master 
  sudo: True
  roles: 
    - { role: workflow, when: install_workflow is defined }
