---
# file: pancancer.yml
# A pan-cancer cluster is basically a SeqWare cluster with some additions
# to support various workflows

# if required, here is where we would port the workaround for Bionimbus and Toyko's cloud in ubuntu_12.04_minimal script
# however, it looks like that might be redundant due to setup_volumes.pl

# do generic SeqWare setup
- include: ../seqware-bag/seqware-install.yml

- hosts: all
  sudo: True
  roles: 
    - { role: workflow-dependencies }
    - { role: genetorrent }

- hosts: master 
  sudo: True
  roles: 
    - { role: workflow-bwa }
