---
# file: pancancer.yml
# A pan-cancer cluster is basically a SeqWare cluster with some additions
# to support various workflows

# if required, here is where we would port the workaround for Bionimbus and Toyko's cloud in ubuntu_12.04_minimal script
# however, it looks like that might be redundant due to setup_volumes.pl

# do generic SeqWare setup
# this is a program for listing all ansible variables,  https://galaxy.ansible.com/list#/roles/646
#- hosts: master
#  roles:
#     - f500.dumpall


- include: ../seqware-bag/seqware-install.yml

- hosts: all
  sudo: True
  vars:
   swap_on: "False"
   sge_hack: "False"
  roles: 
    - { role: mount_device, when: device is defined }
    - { role: workflow-dependencies }
    - { role: mount_device, when: device is defined }
    - { role: genetorrent }
    - { role: workflow-bwa-dependencies, when: ( workflow_name is defined and workflow_name == 'BWA' ) }
    - { role: ebi-custom }

# 9000 equals to aproximately 10 GB of SWAP; we don't want to run the playbook if the instance already has 10 GB of SWAP because the role was most probably already applied.
    - { role: swap-enabled, when: swap_on and ansible_swaptotal_mb < 9000 }

- hosts: master 
  sudo: True
  roles: 
    - { role: workflow, when: install_workflow is defined }
