---
# file: roles/update_workflow/tasks/main.yml

- name: Detect workflows installed
  shell: ls /home/{{ user_name }}/provisioned-bundles/ 
  sudo_user: "{{ user_name }}"
  register: provisioned_bundles
  changed_when: false

#- debug: var=provisioned_bundles.stdout

#- debug: var=workflows

- name: Delete old provisioned bundles
  sudo_user: "{{ user_name }}"
  shell: rm -r *
  args:
     chdir: /home/{{ user_name }}/provisioned-bundles/
  when: '"{{ item }}" in provisioned_bundles.stdout'
  with_items: workflows

- name: Copy workflows
  sudo_user: "{{ user_name }}"
  copy: src={{ item }}.zip dest=/home/seqware/released-bundles/{{ item }}.zip owner=seqware group=seqware mode=0755 force=no
  #when: '"{{ item }}" not in provisioned_bundles.stdout'
  register: workflows_downloaded
  with_items: workflows

     
 # note: zip may already have been cleaned up, this is why we're ignoring errors
- name: Setup bundle permissions
  sudo_user: "{{ user_name }}"
  file: path=/home/{{ user_name }}/released-bundles/{{ item }}.zip owner={{ user_name }} group={{ user_name }}
  when: workflows_downloaded.changed
  with_items: workflows

- name : Install workflow bundles
  sudo_user: "{{ user_name }}"
  shell: /home/{{ user_name }}/bin/seqware bundle install --zip /home/{{ user_name }}/released-bundles/{{ item }}.zip
  when: workflows_downloaded.changed
  args: 
    creates: /home/{{ user_name }}/provisioned-bundles/{{ item }}/  
  with_items: workflows
  register: install_result


- name: Remove workflow bundles
  sudo_user: "{{ user_name }}"
  command: rm /home/{{ user_name }}/released-bundles/{{ item }}.zip removes=/home/{{ user_name }}/released-bundles/{{ item }}.zip
  with_items: workflows
