---
- hosts: all
  sudo: True
  tasks:
  - name: Format sdb
    filesystem: fstype=xfs dev=/dev/{{device}}
  - name: Ensure device is mounted as mnt
    mount: name=/mnt/seqware-oozie src=/dev/{{device}} fstype='xfs' opts=defaults dump=1 passno=2 state=mounted
