---
- name: Install the xfs package
  apt: pkg=xfsprogs state=present

- name: Format the device
  filesystem: fstype=xfs dev=/dev/{{device}}

- name: Ensure device is mounted as mnt
  mount: name=/mnt/seqware-oozie src=/dev/{{device}} fstype='xfs' opts=defaults dump=1 passno=2 state=mounted
