---
# file: roles/seqware-bwa/tasks/main.yml

- name: install bwa workflow dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - liblz-dev 
    - zlib1g-dev 
    - libxml-dom-perl 
    - samtools 
    - libossp-uuid-perl 
    - libjson-perl 
    - libxml-libxml-perl 
    - libtry-tiny-perl 
    - libgd2-noxpm 
    - g++ 
    - dh-autoreconf 
    - libncurses-dev 
    - pkg-config 
    - libgd2-noxpm-dev 
    - libgd2-noxpm 
    - libxml-xpath-perl 

- name: Detect bwa install
  command: ls ~seqware/provisioned-bundles
  register: provisioned_bundles
  changed_when: false

- name: Download bwa workflow 
  get_url: url=http://s3.amazonaws.com/oicr.workflow.bundles/released-bundles/{{ bundle_prefix }}.zip dest=~seqware/released-bundles/ owner=seqware
  when: "'{{ bundle_prefix }}' not in provisioned_bundles.stdout" 
     
  # note: zip may already have been cleaned up, this is why we're ignoring errors
- name: Setup bwa permissions
  file: path=~seqware/released-bundles/{{ bundle_prefix }}.zip owner=seqware group=seqware
  ignore_errors: yes

- name : Install bwa bundle 
  sudo_user: seqware
  shell: ~seqware/bin/seqware bundle install --zip ~seqware/released-bundles/{{ bundle_prefix }}.zip
  args: 
    creates: ~seqware/provisioned-bundles/{{ bundle_prefix }}/  
    
- name: Remove bwa bundle
  command: rm ~seqware/released-bundles/{{ bundle_prefix }}.zip removes=~seqware/released-bundles/{{ bundle_prefix }}.zip
