---
# file: roles/seqware-bwa/tasks/main.yml

- name: Detect bwa install
  command: ls ~{{ user_name }}/provisioned-bundles
  register: provisioned_bundles
  changed_when: false

  # note we need to override the temporary working directory because this bundle is just too big
  # need to use absolute paths, go figure
- name: Download bwa workflow 
  sudo_user: "{{ user_name }}"
  environment:
    TMPDIR: /mnt/home/{{ user_name }}
  shell: wget http://s3.amazonaws.com/oicr.workflow.bundles/released-bundles/{{ bundle_prefix }}.zip
  args:
    chdir: ~{{ user_name }}/released-bundles/
    creates: ~{{ user_name }}/released-bundles/{{ bundle_prefix }}.zip

  when: "'{{ bundle_prefix }}' not in provisioned_bundles.stdout"
  register: bwa_downloaded
     
  # note: zip may already have been cleaned up, this is why we're ignoring errors
- name: Setup bwa permissions
  file: path=~{{ user_name }}/released-bundles/{{ bundle_prefix }}.zip owner={{ user_name }} group={{ user_name }}
  when: bwa_downloaded.changed

- name : Install bwa bundle 
  sudo_user: "{{ user_name }}"
  shell: ~{{ user_name }}/bin/seqware bundle install --zip ~seqware/released-bundles/{{ bundle_prefix }}.zip
  when: bwa_downloaded.changed
  args: 
    creates: ~{{ user_name }}/provisioned-bundles/{{ bundle_prefix }}/  
    
- name: Remove bwa bundle
  command: rm ~{{ user_name }}/released-bundles/{{ bundle_prefix }}.zip removes=~{{ user_name }}/released-bundles/{{ bundle_prefix }}.zip
