---
# file: roles/workflow/tasks/main.yml

- name: Detect workflow install
  command: ls ~seqware/provisioned-bundles
  register: provisioned_bundles
  changed_when: false

  # note we need to override the temporary working directory because this bundle is just too big
  # need to use absolute paths, go figure
- name: Download workflow 
  sudo_user: seqware
  environment:
    TMPDIR: /mnt/home/seqware
  shell: wget http://s3.amazonaws.com/oicr.workflow.bundles/released-bundles/{{ bundle_prefix }}.zip
  args:
    chdir: ~seqware/released-bundles/
    creates: ~seqware/released-bundles/{{ bundle_prefix }}.zip

  when: "'{{ bundle_prefix }}' not in provisioned_bundles.stdout"
  register: workflow_downloaded
     
  # note: zip may already have been cleaned up, this is why we're ignoring errors
- name: Setup workflow permissions
  file: path=~seqware/released-bundles/{{ bundle_prefix }}.zip owner=seqware group=seqware
  when: workflow_downloaded.changed

- name : Install bundle 
  sudo_user: seqware
  shell: ~seqware/bin/seqware bundle install --zip ~seqware/released-bundles/{{ bundle_prefix }}.zip
  when: workflow_downloaded.changed
  args: 
    creates: ~/seqware/provisioned-bundles/{{ bundle_prefix }}/  
    
- name: Remove workflow bundle
  command: rm ~/seqware/released-bundles/{{ bundle_prefix }}.zip removes=~seqware/released-bundles/{{ bundle_prefix }}.zip
