---
# file: roles/seqware-bwa-dependencies/tasks/main.yml

- name: install bwa workflow dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - liblz-dev 
    - zlib1g-dev 
    - libxml-dom-perl 
    - samtools 
    - libossp-uuid-perl 
    - libjson-perl 
    - libxml-libxml-perl 
    - libtry-tiny-perl 
    - libgd2-noxpm 
    - g++ 
    - dh-autoreconf 
    - libncurses-dev 
    - pkg-config 
    - libgd2-noxpm-dev 
    - libgd2-noxpm 
    - libxml-xpath-perl 

- name: Add proper permissions to the "/mnt/datastore" directory
  file: path=/mnt/datastore state=directory owner=seqware group=root mode=0777

- name: Add proper permissions to the "/mnt/seqware-oozie" directory
  file: path=/mnt/seqware-oozie state=directory owner=seqware group=root mode=0755

- name: Template over SGE h_vmem changes
  template: src=master.ini.j2 dest=/tmp/master.ini
  notify: apply qconf h_vmem changes
  when: sge_hack

- name: Copy over complex config needed qconf
  copy: src=complex dest=/tmp/complex mode=0644
  notify: apply qconf complex changes
  when: sge_hack
