---

- name: Run HelloWorld as a test workflow
  shell: docker run --rm -h master -t -v /var/run/docker.sock:/var/run/docker.sock -v /datastore:/datastore -v /workflows/Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_1.1.0:/workflow  -i seqware/seqware_whitestar_pancancer seqware bundle launch --dir /workflow --no-metadata

#  docker:
#    image: seqware/seqware_full
#    state: started
#    hostname: master
#    command: /start.sh "seqware bundle launch --dir /workflow" 
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /datastore:/datastore
#      - /workflows/Workflow_Bundle_HelloWorld_1.0-SNAPSHOT_SeqWare_1.1.0:/workflow
#  tags:
#    - test_workflow
